POST http://localhost:8090/api/account/member/email
Content-Type: application/json

{
  "email": "insub2004@naver.com"
}

###
GET http://localhost:8090/api/account/member/email
Content-Type: application/json

{
  "email": "insub2004@naver.com",
  "certificationNumber": "249907"
}