POST http://localhost:8090/api/account/member/register
Content-Type: application/json

{
  "id": "testId",
  "password": "testPassword",
  "email": "test@test.com",
  "roles": 2
}

###
POST http://localhost:8090/api/account/member/register
Content-Type: application/json

{
  "id": "testId7",
  "password": "testPassword",
  "email": "test@test.com",
  "roles": 3
}


###
GET http://localhost:8090/api/account/member/testId
Accept: application/json

###
GET http://localhost:8090/api/account/member/testId3
Accept: application/json

###
PUT http://localhost:8090/api/account/member/modify/testId
Content-Type: application/json

{
  "id" : "testId",
  "password" : "etoq43odg",
  "email" : "hello@test.com",
  "role": 2
}